# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1avf7ad-8LJvrqumgX5YR60YWaiLGElzW
"""

from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
print(iris['DESCR'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.90)

clf = tree.DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

import pandas as pd
print("\nMatriz de confunsao detalhada: \n",
      pd.crosstab(y_test, predictions, rownames=['Real'], colnames=['Predito'],
                  margins=True, margins_name='Todos'))

import sklearn.metrics as metrics
print("Relatório sobre a qualidade:\n")
print(metrics.classification_report(y_test, predictions, target_names=['Setosa', 'Versicolor', 'Virginica']))

import graphviz
dot_data = tree.export_graphviz(clf, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("iris")
dot_data = tree.export_graphviz(clf, out_file=None, 
                                feature_names=iris.feature_names, 
                                class_names = iris.target_names,
                                filled = True, rounded = True,
                                special_characters=True)
graph = graphviz.Source(dot_data, format="png")
graph